version: 0.0
os: ubuntu
files:
  - source: /
    destination: /var/www/ruby
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      runas: root
#   ApplicationStop:
#     - location: scripts/applicationStop.sh
#       runas: root
