version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ruby
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: deploy
  ApplicationStart:
    - location: scripts/applicationStart.sh
      runas: deploy
#   ApplicationStop:
#     - location: scripts/applicationStop.sh
#       runas: root
